### ISSUE TITLE
[Firmware Request]: <Brand> - <ZW Number> - <Prod Number> 

### ISSUE THREAD

**Issue by trentjw** [jascoproducts/firmware#41] opened 2022-06-13 23:57 UTC
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW4005

### Product Number

14291

**Comment by DAVe3283** [comment] 2022-06-14 02:40
Duplicate of #12

**Comment by jascoproducts** [comment] 2022-06-14 15:46
@trentjw Please follow Issue #12 for updates.

**Closed by jascoproducts** 2022-06-14 15:46 UTC
